# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 10 Oct 2017 16:36:15 +0000
*               @ALL          1
*               @user         8
